package org.drizzly.persistence.dto;
// Generated 17 Oct, 2015 9:14:35 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DrMaStudent generated by hbm2java
 */
public class DrMaStudent  implements java.io.Serializable {


     private Long stId;
     private DrMaCategory drMaCategory;
     private String stName;
     private Date stJoinedDate;
     private String stFeesMode;
     private String stFatherName;
     private String stMotherName;
     private Date stRelievedDate;
     private String stAddress;
     private String stCity;
     private String stState;
     private String stPincode;
     private String stCountry;
     private String stMobile1;
     private String stMobile2;
     private String stEmail1;
     private Set drTrFeesDues = new HashSet(0);

    public DrMaStudent() {
    }

	
    public DrMaStudent(DrMaCategory drMaCategory, String stName, Date stJoinedDate, String stFeesMode, String stFatherName, String stMotherName, String stAddress, String stCity, String stState, String stPincode, String stCountry, String stMobile1) {
        this.drMaCategory = drMaCategory;
        this.stName = stName;
        this.stJoinedDate = stJoinedDate;
        this.stFeesMode = stFeesMode;
        this.stFatherName = stFatherName;
        this.stMotherName = stMotherName;
        this.stAddress = stAddress;
        this.stCity = stCity;
        this.stState = stState;
        this.stPincode = stPincode;
        this.stCountry = stCountry;
        this.stMobile1 = stMobile1;
    }
    public DrMaStudent(DrMaCategory drMaCategory, String stName, Date stJoinedDate, String stFeesMode, String stFatherName, String stMotherName, Date stRelievedDate, String stAddress, String stCity, String stState, String stPincode, String stCountry, String stMobile1, String stMobile2, String stEmail1, Set drTrFeesDues) {
       this.drMaCategory = drMaCategory;
       this.stName = stName;
       this.stJoinedDate = stJoinedDate;
       this.stFeesMode = stFeesMode;
       this.stFatherName = stFatherName;
       this.stMotherName = stMotherName;
       this.stRelievedDate = stRelievedDate;
       this.stAddress = stAddress;
       this.stCity = stCity;
       this.stState = stState;
       this.stPincode = stPincode;
       this.stCountry = stCountry;
       this.stMobile1 = stMobile1;
       this.stMobile2 = stMobile2;
       this.stEmail1 = stEmail1;
       this.drTrFeesDues = drTrFeesDues;
    }
   
    public Long getStId() {
        return this.stId;
    }
    
    public void setStId(Long stId) {
        this.stId = stId;
    }
    public DrMaCategory getDrMaCategory() {
        return this.drMaCategory;
    }
    
    public void setDrMaCategory(DrMaCategory drMaCategory) {
        this.drMaCategory = drMaCategory;
    }
    public String getStName() {
        return this.stName;
    }
    
    public void setStName(String stName) {
        this.stName = stName;
    }
    public Date getStJoinedDate() {
        return this.stJoinedDate;
    }
    
    public void setStJoinedDate(Date stJoinedDate) {
        this.stJoinedDate = stJoinedDate;
    }
    public String getStFeesMode() {
        return this.stFeesMode;
    }
    
    public void setStFeesMode(String stFeesMode) {
        this.stFeesMode = stFeesMode;
    }
    public String getStFatherName() {
        return this.stFatherName;
    }
    
    public void setStFatherName(String stFatherName) {
        this.stFatherName = stFatherName;
    }
    public String getStMotherName() {
        return this.stMotherName;
    }
    
    public void setStMotherName(String stMotherName) {
        this.stMotherName = stMotherName;
    }
    public Date getStRelievedDate() {
        return this.stRelievedDate;
    }
    
    public void setStRelievedDate(Date stRelievedDate) {
        this.stRelievedDate = stRelievedDate;
    }
    public String getStAddress() {
        return this.stAddress;
    }
    
    public void setStAddress(String stAddress) {
        this.stAddress = stAddress;
    }
    public String getStCity() {
        return this.stCity;
    }
    
    public void setStCity(String stCity) {
        this.stCity = stCity;
    }
    public String getStState() {
        return this.stState;
    }
    
    public void setStState(String stState) {
        this.stState = stState;
    }
    public String getStPincode() {
        return this.stPincode;
    }
    
    public void setStPincode(String stPincode) {
        this.stPincode = stPincode;
    }
    public String getStCountry() {
        return this.stCountry;
    }
    
    public void setStCountry(String stCountry) {
        this.stCountry = stCountry;
    }
    public String getStMobile1() {
        return this.stMobile1;
    }
    
    public void setStMobile1(String stMobile1) {
        this.stMobile1 = stMobile1;
    }
    public String getStMobile2() {
        return this.stMobile2;
    }
    
    public void setStMobile2(String stMobile2) {
        this.stMobile2 = stMobile2;
    }
    public String getStEmail1() {
        return this.stEmail1;
    }
    
    public void setStEmail1(String stEmail1) {
        this.stEmail1 = stEmail1;
    }
    public Set getDrTrFeesDues() {
        return this.drTrFeesDues;
    }
    
    public void setDrTrFeesDues(Set drTrFeesDues) {
        this.drTrFeesDues = drTrFeesDues;
    }




}


