package org.drizzly.persistence.dto;
// Generated 17 Oct, 2015 9:14:35 PM by Hibernate Tools 4.3.1

import java.math.BigInteger;




/**
 * DrMaFees generated by hbm2java
 */
public class DrMaFees  implements java.io.Serializable {


     private Long feId;
     private DrMaCategory drMaCategory;
     private BigInteger feAmount;

    public DrMaFees() {
    }

    public DrMaFees(DrMaCategory drMaCategory, BigInteger feAmount) {
       this.drMaCategory = drMaCategory;
       this.feAmount = feAmount;
    }
   
    public Long getFeId() {
        return this.feId;
    }
    
    public void setFeId(Long feId) {
        this.feId = feId;
    }
    public DrMaCategory getDrMaCategory() {
        return this.drMaCategory;
    }
    
    public void setDrMaCategory(DrMaCategory drMaCategory) {
        this.drMaCategory = drMaCategory;
    }
    public BigInteger getFeAmount() {
        return this.feAmount;
    }
    
    public void setFeAmount(BigInteger feAmount) {
        this.feAmount = feAmount;
    }




}


