package org.drizzly.persistence.dto;
// Generated 17 Oct, 2015 9:14:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DrMaCategory generated by hbm2java
 */
public class DrMaCategory  implements java.io.Serializable {


     private Long ctId;
     private String ctName;
     private Set drMaFeeses = new HashSet(0);
     private Set drMaStudents = new HashSet(0);

    public DrMaCategory() {
    }

	
    public DrMaCategory(String ctName) {
        this.ctName = ctName;
    }
    public DrMaCategory(String ctName, Set drMaFeeses, Set drMaStudents) {
       this.ctName = ctName;
       this.drMaFeeses = drMaFeeses;
       this.drMaStudents = drMaStudents;
    }
   
    public Long getCtId() {
        return this.ctId;
    }
    
    public void setCtId(Long ctId) {
        this.ctId = ctId;
    }
    public String getCtName() {
        return this.ctName;
    }
    
    public void setCtName(String ctName) {
        this.ctName = ctName;
    }
    public Set getDrMaFeeses() {
        return this.drMaFeeses;
    }
    
    public void setDrMaFeeses(Set drMaFeeses) {
        this.drMaFeeses = drMaFeeses;
    }
    public Set getDrMaStudents() {
        return this.drMaStudents;
    }
    
    public void setDrMaStudents(Set drMaStudents) {
        this.drMaStudents = drMaStudents;
    }




}


