package org.drizzly.persistence.dto;
// Generated 17 Oct, 2015 9:14:35 PM by Hibernate Tools 4.3.1


import java.math.BigInteger;
import java.util.Date;

/**
 * DrTrLoan generated by hbm2java
 */
public class DrTrLoan  implements java.io.Serializable {


     private Long lnId;
     private DrMaEmployee drMaEmployee;
     private BigInteger lnAmount;
     private Date lnReceivedDate;
     private Date lnClosedDate;

    public DrTrLoan() {
    }

	
    public DrTrLoan(DrMaEmployee drMaEmployee, BigInteger lnAmount, Date lnReceivedDate) {
        this.drMaEmployee = drMaEmployee;
        this.lnAmount = lnAmount;
        this.lnReceivedDate = lnReceivedDate;
    }
    public DrTrLoan(DrMaEmployee drMaEmployee, BigInteger lnAmount, Date lnReceivedDate, Date lnClosedDate) {
       this.drMaEmployee = drMaEmployee;
       this.lnAmount = lnAmount;
       this.lnReceivedDate = lnReceivedDate;
       this.lnClosedDate = lnClosedDate;
    }
   
    public Long getLnId() {
        return this.lnId;
    }
    
    public void setLnId(Long lnId) {
        this.lnId = lnId;
    }
    public DrMaEmployee getDrMaEmployee() {
        return this.drMaEmployee;
    }
    
    public void setDrMaEmployee(DrMaEmployee drMaEmployee) {
        this.drMaEmployee = drMaEmployee;
    }
    public BigInteger getLnAmount() {
        return this.lnAmount;
    }
    
    public void setLnAmount(BigInteger lnAmount) {
        this.lnAmount = lnAmount;
    }
    public Date getLnReceivedDate() {
        return this.lnReceivedDate;
    }
    
    public void setLnReceivedDate(Date lnReceivedDate) {
        this.lnReceivedDate = lnReceivedDate;
    }
    public Date getLnClosedDate() {
        return this.lnClosedDate;
    }
    
    public void setLnClosedDate(Date lnClosedDate) {
        this.lnClosedDate = lnClosedDate;
    }




}


