CREATE TABLE IF NOT EXISTS DrizzlyDB.DR_MA_ADDRESS (
  AD_ID BIGINT(10) NOT NULL AUTO_INCREMENT,
  AD_ADDRESS VARCHAR(500) NOT NULL,
  AD_CITY VARCHAR(100) NOT NULL,
  AD_STATE VARCHAR(100) NOT NULL,
  AD_PINCODE VARCHAR(50) NOT NULL,
  AD_COUNTRY VARCHAR(50) NOT NULL,
  AD_MOBILE1 VARCHAR(15) NOT NULL,
  AD_MOBILE2 VARCHAR(15) NULL,
  AD_EMAIL1 VARCHAR(150) NULL,
  AD_EMAIL2 VARCHAR(150) NULL,
  PRIMARY KEY (AD_ID))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS DrizzlyDB.DR_MA_CATEGORY (
  CT_ID BIGINT(10) NOT NULL AUTO_INCREMENT,
  CT_NAME VARCHAR(100) NOT NULL,
  PRIMARY KEY (CT_ID))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS DrizzlyDB.DR_MA_EMPLOYEE (
  EM_ID BIGINT(10) NOT NULL AUTO_INCREMENT,
  EM_NAME VARCHAR(100) NOT NULL,
  EM_JOIN_DATE DATE NOT NULL,
  EM_SALARY DECIMAL(10,0) NOT NULL,
  EM_RELEIVED_DATE DATE NULL,
  EM_AD_ID BIGINT(10) NOT NULL,
  PRIMARY KEY (EM_ID),
  INDEX FK_DR_MA_EMPLOYEE_AD_ID_idx (EM_AD_ID ASC),
  CONSTRAINT FK_DR_MA_EMPLOYEE_AD_ID
    FOREIGN KEY (EM_AD_ID)
    REFERENCES DrizzlyDB.DR_MA_ADDRESS (AD_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
PACK_KEYS = DEFAULT
ROW_FORMAT = DEFAULT;

CREATE TABLE IF NOT EXISTS DrizzlyDB.DR_MA_FEES (
  FE_ID BIGINT(10) NOT NULL AUTO_INCREMENT,
  FE_CT_ID BIGINT(10) NOT NULL,
  FE_AMOUNT DECIMAL(10,0) NOT NULL,
  PRIMARY KEY (FE_ID),
  INDEX FK_DR_FEES_CT_ID_idx (FE_CT_ID ASC),
  CONSTRAINT FK_DR_FEES_CT_ID
    FOREIGN KEY (FE_CT_ID)
    REFERENCES DrizzlyDB.DR_MA_CATEGORY (CT_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS DrizzlyDB.DR_MA_STUDENT (
  ST_ID BIGINT(10) NOT NULL AUTO_INCREMENT,
  ST_NAME VARCHAR(100) NOT NULL,
  ST_JOINED_DATE DATE NOT NULL,
  ST_CT_ID BIGINT(10) NOT NULL,
  ST_FEES_MODE VARCHAR(100) NOT NULL,
  ST_FATHER_NAME VARCHAR(100) NOT NULL,
  ST_MOTHER_NAME VARCHAR(100) NOT NULL,
  ST_RELIEVED_DATE DATE NULL,
  ST_AD_ID BIGINT(10) NOT NULL,
  INDEX FK_DR_MA_STUDENT_CT_ID_idx (ST_CT_ID ASC),
  PRIMARY KEY (ST_ID),
  INDEX FK_DR_MA_ADDRESS_AD_ID_idx (ST_AD_ID ASC),
  CONSTRAINT FK_DR_MA_STUDENT_CT_ID
    FOREIGN KEY (ST_CT_ID)
    REFERENCES DrizzlyDB.DR_MA_CATEGORY (CT_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_DR_MA_ADDRESS_AD_ID
    FOREIGN KEY (ST_AD_ID)
    REFERENCES DrizzlyDB.DR_MA_ADDRESS (AD_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
ROW_FORMAT = DEFAULT;

CREATE TABLE IF NOT EXISTS DrizzlyDB.DR_TR_FEES_DUE (
  FP_ID BIGINT(10) NOT NULL AUTO_INCREMENT,
  FP_ST_ID BIGINT(10) NOT NULL,
  FP_AMOUNT_PAID DECIMAL(10,0) NOT NULL,
  FP_PAID_DATE DATE NOT NULL,
  FP_MONTH VARCHAR(45) NULL,
  FD_TERM VARCHAR(45) NULL,
  FD_YEARLY VARCHAR(45) NULL,
  PRIMARY KEY (FP_ID),
  INDEX FK_DR_FEES_PAY_ST_ID_idx (FP_ST_ID ASC),
  CONSTRAINT FK_DR_FEES_PAY_ST_ID
    FOREIGN KEY (FP_ST_ID)
    REFERENCES DrizzlyDB.DR_MA_STUDENT (ST_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS DrizzlyDB.DR_TR_LOAN (
  LN_ID BIGINT(10) NOT NULL AUTO_INCREMENT,
  LN_EM_ID BIGINT(10) NOT NULL,
  LN_AMOUNT DECIMAL(10,0) NOT NULL,
  LN_RECEIVED_DATE DATE NOT NULL,
  LN_CLOSED_DATE DATE NULL,
  PRIMARY KEY (LN_ID),
  INDEX FK_DR_TR_EMP_ID_idx (LN_EM_ID ASC),
  CONSTRAINT FK_DR_EMP_LOAN_ID
    FOREIGN KEY (LN_EM_ID)
    REFERENCES DrizzlyDB.DR_MA_EMPLOYEE (EM_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS DrizzlyDB.DR_TR_LOAN_DUE (
  LP_ID BIGINT(10) NOT NULL AUTO_INCREMENT,
  LP_EM_ID BIGINT(10) NOT NULL,
  LP_LN_ID BIGINT(10) NOT NULL,
  LP_AMOUNT_PAID DECIMAL(10,0) NOT NULL,
  LP_DATE DATE NOT NULL,
  PRIMARY KEY (LP_ID),
  INDEX FK_DR_EMP_LOAN_PAYMENT_ID_idx (LP_EM_ID ASC),
  INDEX FK_DR_EM_LN_PAY_LN_ID_idx (LP_LN_ID ASC),
  CONSTRAINT FK_DR_EM_LN_PAY_EMP_ID
    FOREIGN KEY (LP_EM_ID)
    REFERENCES DrizzlyDB.DR_MA_EMPLOYEE (EM_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_DR_EM_LN_PAY_LN_ID
    FOREIGN KEY (LP_LN_ID)
    REFERENCES DrizzlyDB.DR_TR_LOAN (LN_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;